#pragma config(Motor,  port9,           righttowertop, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           righttowermid, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           righttowerlow, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rightdrive,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           leftdrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           lefttowertop,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port2,           lefttowermid,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port1,          lefttowerlow,  tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void robot()
{		if(vexRT(Btn7U)==1)
	{
		motor[righttowertop]=127;
		motor[righttowermid]=127;
		motor[righttowerlow]=127;
		motor[lefttowertop]=127;
		motor[lefttowermid]=127;
		motor[lefttowerlow]=127;
	}
	else if(vexRT(Btn7D)==1)
	{
		motor[righttowertop]=-127;
		motor[righttowermid]=-127;
		motor[righttowerlow]=-127;
		motor[lefttowertop]=-127;
		motor[lefttowermid]=-127;
		motor[lefttowerlow]=-127;
	}
	else if(vexRT(Btn7L)==1)
	{motor[claw]=127;
	}
	else if(vexRT(Btn7R)==1)
	{motor[claw]=-127;
	}

	else
	{
		motor[righttowertop]=0;
		motor[righttowermid]=0;
		motor[righttowerlow]=0;
		motor[lefttowertop]=0;
		motor[lefttowermid]=0;
		motor[lefttowerlow]=0;
		motor[rightdrive]=0;
		motor[leftdrive]=0;
	}


	if(vexRT(Btn8R)==1)
	{
		motor[claw]=127;
	}
	else
	{
		motor[claw]=0;
	}
	if(vexRT[Ch3] > 10 || vexRT[Ch4] > 10 || vexRT[Ch3] < -10 || vexRT[Ch4] < -10) //JOYSTICK DEADBAND
		{
			motor[LeftMotor] = (vexRT[Ch3] + vexRT[Ch4]);
			motor[LeftdriveY] = (vexRT[Ch3] + vexRT[Ch4]);
			motor[RightMotor] = (vexRT[Ch3] - vexRT[Ch4]);
			motor[RightdriveY] = (vexRT[Ch3] - vexRT[Ch4]);
}
task main()
{
	while(1)
	{
		robot();
		while(vexRT(Btn8R)==1)
		{wait1Msec(100);
			while(vexRT(Btn8R)==0)
			{motor[claw]=75;
				robot();
			}
			wait1Msec(100);
		}


	}
}
