#pragma config(Motor,  port1,           ltl,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           ltm,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ltt,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           clawl,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           ld,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rd,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           clawr,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           rtm,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rtt,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rtl,           tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(1==1)
	{
		if(vexRT[Ch3] > 10 || vexRT[Ch4] > 10 || vexRT[Ch3] < -10 || vexRT[Ch4] < -10) //JOYSTICK DEADBAND
		{
			motor[ld]=(vexRT[Ch4]+vexRT[Ch3]);
			motor[rd]=(vexRT[Ch4]-vexRT[Ch3]);
		}
		else
		{
			motor[ld]=0;
			motor[rd]=0;
		}

		motor[ltl]=vexRT[Ch2];
		motor[ltm]=vexRT[Ch2];
		motor[ltt]=vexRT[Ch2];
		motor[rtl]=vexRT[Ch2];
		motor[rtm]=vexRT[Ch2];
		motor[rtt]=vexRT[Ch2];

		if(vexRT[Btn5U]==1)
		{
			motor[clawl]=127;
			motor[clawr]=127;
		}
		else if(vexRT[Btn6U]==1)
		{
			motor[clawl]=-127;
			motor[clawr]=-127;
		}
		else
		{
			motor[clawl]=0;
			motor[clawr]=0;
		}
	}

}
