#pragma config(Sensor, dgtl1,  solenoid,       sensorDigitalOut)
#pragma config(Motor,  port1,           LB,            tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RightdriveY,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LM,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           LT,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RT,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RM,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           LeftdriveY,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LeftMotor,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          RB,            tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{

	while (1==1)
	{
		if(vexRT[Ch3] > 10 || vexRT[Ch4] > 10 || vexRT[Ch3] < -10 || vexRT[Ch4] < -10) //JOYSTICK DEADBAND
		{
			motor[LeftMotor] = (vexRT[Ch3] + vexRT[Ch4]);
			motor[LeftdriveY] = (vexRT[Ch3] + vexRT[Ch4]);
			motor[RightMotor] = (vexRT[Ch3] - vexRT[Ch4]);
			motor[RightdriveY] = (vexRT[Ch3] - vexRT[Ch4]);
		}
		else
		{
			motor[LeftMotor] = 0;
			motor[LeftdriveY] = 0;
			motor[RightMotor] = 0;
			motor[RightdriveY] = 0;

		}

		if(vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[LT] = 127;
			motor[LM] = 127;
			motor[LB] = 127;
			motor[RT] = 127;
			motor[RM] = 127;
			motor[RB] = 127;
		}
		else if(vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[LT] = -127;
			motor[LM] = -127;
			motor[LB] = -127;
			motor[RT] = -127;
			motor[RM] = -127;
			motor[RB] = -127;
		}
		else if(vexRT[Ch2] > 10 || vexRT[Ch2] < -10)
		{
			motor[LT] = vexRT[Ch2];
			motor[LM] = vexRT[Ch2];
			motor[LB] = vexRT[Ch2];
			motor[RT] = vexRT[Ch2];
			motor[RM] = vexRT[Ch2];
			motor[RB] = vexRT[Ch2];
		}
		else if(vexRT[Btn6U]==1)      //Else, if bitton 6U is pressed...
		{
			SensorValue[solenoid]=1;    //Switch the solenoid
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[LT] = 0;
			motor[LM] = 0;
			motor[LB] = 0;
			motor[RT] = 0;
			motor[RM] = 0;
			motor[RB] = 0;      	//...stop the arm.
		}
		if(vexRT[Btn6U]==1)      //Else, if bitton 6U is pressed...
		{
			SensorValue[solenoid]=1;    //Switch the solenoid
		}
		else                      		//Else (neither button is pressed)...
		{
			SensorValue[solenoid]=0;
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
