// by Jason Becker
// since 12/11/16
// for VCAT Robotics
/*#pragma config(Sensor, in1,    armpot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  clawswitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  armswitch,      sensorTouch)
#pragma config(Sensor, dgtl3,  lencoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rencoder,       sensorQuadEncoder)
#pragma config(Motor,  port1,           ltl,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           ltm,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ltt,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           clawl,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           ld,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rd,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           clawr,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           rtm,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rtt,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rtl,           tmotorVex393HighSpeed_HBridge, openLoop)*/
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma DebuggerWindows("debugStream")
task main{
	//~~~~~~~~~~~~This section should be called from the Driver Control using #include"Recorder.c"
	//tempate is (Button=Value, Time)
void Run()
{vexRT[Ch2]=vexRT[Ch2],Time;
}
task main
{

}
}
int Time=200;	//in Ms how often will the program check conditions
writeDebugStreamLine("vexRT[Ch1]=%d, %t", vexRT[Ch1], Time); //Time is an assumption of how long the button value is given based on
//writeDebugStream(", %t",Time) //use this if the compilser cannot correctly use the above statement
writeDebugStreamLine("vexRT[Ch2]=%d", vexRT[Ch2]);
writeDebugStreamLine("vexRT[Ch3]=%d", vexRT[Ch3]);
writeDebugStreamLine("vexRT[Ch4]=%d", vexRT[Ch4]);
writeDebugStreamLine("vexRT[Btn5U]=%d", vexRT[Btn5U]);
writeDebugStreamLine("vexRT[Btn5D]=%d", vexRT[Btn5D]);
writeDebugStreamLine("vexRT[Btn6U]=%d", vexRT[Btn6U]);
writeDebugStreamLine("vexRT[Btn6D]=%d", vexRT[Btn6D]);
writeDebugStreamLine("vexRT[Btn7U]=%d", vexRT[Btn7U]);
writeDebugStreamLine("vexRT[Btn7D]=%d", vexRT[Btn7D]);
writeDebugStreamLine("vexRT[Btn7L]=%d", vexRT[Btn7L]);
writeDebugStreamLine("vexRT[Btn7R]=%d", vexRT[Btn7R]);
writeDebugStreamLine("vexRT[Btn8U]=%d", vexRT[Btn8U]);
writeDebugStreamLine("vexRT[Btn8D]=%d", vexRT[Btn8D]);
writeDebugStreamLine("vexRT[Btn8L]=%d", vexRT[Btn8L]);
writeDebugStreamLine("vexRT[Btn8R]=%d", vexRT[Btn8R]);
wait1Msec(
wait1Msec(Time);//wait for Time before checking the button values again
}
