// by Jason Becker
// since 12/11/16
// for VCAT Robotics
/*#pragma config(Sensor, in1,    armpot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  clawswitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  armswitch,      sensorTouch)
#pragma config(Sensor, dgtl3,  lencoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  rencoder,       sensorQuadEncoder)
#pragma config(Motor,  port1,           ltl,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           ltm,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ltt,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           clawl,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           ld,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rd,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           clawr,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           rtm,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rtt,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rtl,           tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*/
//#pragma DebuggerWindows("debugStream")
//~~~~~~~~~~~~This section should be called from the Driver Control using #include"Recorder.c"
//tempate is (Button=Value, Time)
/*	void Run()
{vexRT[Ch2]=vexRT[Ch2],Time;
}*/
//task main
//{
//clearDebugStream();
//while(1)
//{


//MAKE SURE #pragma DebuggerWindows("debugStream") IS IN MAIN CODE

int Time=200;	//in Ms how often will the program check conditions
if (vexRT[Ch1]>10||vexRT[Ch1]<-10) //theses values can be changed based on bandwidth
{writeDebugStreamLine("vexRT[Ch1]=%d);", vexRT[Ch1]);} //Time is an assumption of how long the button value is given based on
if (vexRT[Ch2]>10||vexRT[Ch2]<-10)
{writeDebugStreamLine("vexRT[Ch2]=%d;", vexRT[Ch2]);}
if (vexRT[Ch3]>10||vexRT[Ch3]<-10)
{writeDebugStreamLine("vexRT[Ch3]=%d;", vexRT[Ch3]);}
if (vexRT[Ch4]>10||vexRT[Ch4]<-10)
{writeDebugStreamLine("vexRT[Ch4]=%d;", vexRT[Ch4]);}
if (vexRT[Btn5U]>0)
{writeDebugStreamLine("vexRT[Btn5U]=%d;", vexRT[Btn5U]);}
if (vexRT[Btn5D]>0)
{writeDebugStreamLine("vexRT[Btn5D]=%d", vexRT[Btn5D]);}
//	writeDebugStream(", %t",Time);}
if (vexRT[Btn6U]>0)
{writeDebugStreamLine("vexRT[Btn6U]=%d", vexRT[Btn6U]);}
//	writeDebugStream(", %t",Time);}
if (vexRT[Btn6D]>0)
{writeDebugStreamLine("vexRT[Btn6D]=%d", vexRT[Btn6D]);}
//writeDebugStream(", %t",Time);}
if (vexRT[Btn7U]>0)
{writeDebugStreamLine("vexRT[Btn7U]=%d", vexRT[Btn7U]);}
//writeDebugStream(", %t",Time);}
if (vexRT[Btn7D]>0)
{writeDebugStreamLine("vexRT[Btn7D]=%d", vexRT[Btn7D]);}
//writeDebugStream(", %t",Time);}
if (vexRT[Btn7L]>0)
{writeDebugStreamLine("vexRT[Btn7L]=%D", vexRT[Btn7L]);}
//writeDebugStream(", %t",Time);}
if (vexRT[Btn7R]>0)
{writeDebugStreamLine("vexRT[Btn7R]=%d", vexRT[Btn7R]);}
//writeDebugStream(", %t",Time);}
if (vexRT[Btn8U]>0)
{writeDebugStreamLine("vexRT[Btn8U]=%d", vexRT[Btn8U]);}
//writeDebugStream(", %t",Time);}
if (vexRT[Btn8D]>0)
{writeDebugStreamLine("vexRT[Btn8D]=%d", vexRT[Btn8D]);}
//writeDebugStream(", %t",Time);}
if (vexRT[Btn8L]>0)
{writeDebugStreamLine("vexRT[Btn8L]=%d", vexRT[Btn8L]);}
//writeDebugStream(", %t",Time);}
if (vexRT[Btn8R]>0)
{writeDebugStreamLine("vexRT[Btn8R]=%d", vexRT[Btn8R]);}
//writeDebugStream(", %t",Time);}
writeDebugStreamLine("wait1Msec(%d);", Time);
wait1Msec(Time);//wait for Time before checking the button values again. the way this is currently coded this may also pause the driving controls while recording
//#include Stop //inclue Stop.c which stops all motors
//}
