#pragma config(Sensor, in1,    armpot,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  clawswitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  armswitch,      sensorTouch)
#pragma config(Sensor, dgtl3,  rencoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  lencoder,       sensorQuadEncoder)
#pragma config(Motor,  port1,           ltl,           tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           ltm,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ltt,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           clawl,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           ld,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rd,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           clawr,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           rtm,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rtt,           tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          rtl,           tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void resetencoders(){SensorValue[rencoder]=0; SensorValue[lencoder]=0;}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void moveArm( int pot, int speed )
{
	while( SensorValue[armpot] >= pot )
	{
		motor[ltl]=speed;
		motor[ltm]=speed;
		motor[ltt]=speed;
		motor[rtl]=speed;
		motor[rtm]=speed;
		motor[rtt]=speed;
	}
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void moveArms(int speed )
{
	while( SensorValue[armswitch]==0 )
	{
		motor[ltl]=speed;
		motor[ltm]=speed;
		motor[ltt]=speed;
		motor[rtl]=speed;
		motor[rtm]=speed;
		motor[rtt]=speed;
	}
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void armStall( int speed )
{
	motor[ltl]=speed;
	motor[ltm]=speed;
	motor[ltt]=speed;
	motor[rtl]=speed;
	motor[rtm]=speed;
	motor[rtt]=speed;
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void moveClaw(int speed )
{
	while( SensorValue[clawswitch]==0 )
	{
		motor[clawr]=speed;
		motor[clawl]=speed;
	}
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void moveRob( int time, int speed )
{

	motor[rd]=-speed;
	motor[ld]=speed;
	wait1Msec(time);
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void turnRob( int time, int speed, int direction ) // direction = -1 for left turn ; direction = 1 for right turn
{

	motor[rd]=speed;
	motor[ld]=speed*direction;
	wait1Msec(time);
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void motorsOff()
{
	motor[ltl]=0;
	motor[ltm]=0;
	motor[ltt]=0;
	motor[rtl]=0;
	motor[rtm]=0;
	motor[rtt]=0;
	motor[rd]=0;
	motor[ld]=0;
	motor[clawl]=0;
	motor[clawr]=0;
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
task main()
{ resetencoders();
	moveRob(.5,-100);
	wait1Msec(500);
	moveArm( 2700, 100 );
	motorsOff();
	armStall( 5 );
	moveClaw(127 );
	motorsOff();
	moveRob( 1700, 100 );
	motorsOff();
	wait1Msec(200);
	moveRob( 800, -100 );
	motorsOff();
	moveArm( 4095, -100 );
	motorsOff();
	turnRob(1100, 40, 1);
	motorsOff();
	delay(500);
	moveRob( 800, -100);
	motorsOff();
	wait1Msec(200);
	moveArms(-100);
	wait1Msec(1000);
	motorsOff();
	moveRob(1000,100);
	motorsOff();//
	motor[clawr]=-100;
	motor[clawl]=-100;
	wait1Msec(500);
	motor[clawr]=-10;
	motor[clawl]=-10;
	turnRob(1500, 75, 1);
	motorsOff();
	motor[clawr]=-10;
	motor[clawl]=-10;
	moveRob( 1700, -100 );
	moveArm( 2000, 100 );
		moveClaw(127 );

}
