#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in2,    leftLine,       sensorLineFollower)
#pragma config(Sensor, in3,    midLine,        sensorLineFollower)
#pragma config(Sensor, in4,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in5,    punchIR,        sensorAnalog)
#pragma config(Sensor, in8,    BackUpBattery,  sensorAnalog)
#pragma config(Sensor, dgtl1,  ArmStop,        sensorTouch)
#pragma config(Sensor, dgtl3,  LeftEnc,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  clawL,          sensorDigitalOut)
#pragma config(Sensor, dgtl6,  clawR,          sensorDigitalOut)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl11, ArmEnc,         sensorQuadEncoder)
#pragma config(Motor,  port1,           LM,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftArmY,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           R1,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightArmM,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           R2,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftArmM,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           L1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightArmY,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RM,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(45)
#pragma userControlDuration(75)

#define DEBUG 1
bool firstRun = false;				//PUNCHER TIMING
int pistonActive = 0, pistonCount=0;
///////////////////////////BEGIN INCLUDED FILES
int alliance = 4;
int autonomousN = 5;
//int stage = 1;
int MoveCounter = 0;
//int FailSafeEngaged = 0;
//float LastError=0;
#include "vex.c"
//#include "BasicMovements.c"
//#include "autovoids.c"
#include "DrivingCode.c"
#include "FUNCTIONS.c"
void pre_auton()
{
	bStopTasksBetweenModes = true;
#include "PreAuto.c";
}

task autonomous()
{
	clearDebugStream();
	//#include "recordautoLeft.c"
	//#include "recordautoRight.c"
#include "TESTERAUTO.c"
}

task usercontrol()
{clearDebugStream();
	//#include "DriverControl3.c" //blank is IDK, 2 is old, 3 is New
	//AlphaRecorder();
	//#include "AlphaRecorder.c"
	#include "MasterRecorderCode.c";

}
