#pragma config(Sensor, in1,    pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rencoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  lencoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  limit,          sensorTouch)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_cm)
#pragma config(Motor,  port1,           left,          tmotorVex269_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port3,           arm,           tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           claw,          tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex269_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("debugStream")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
int fullRotation=(360); //12.56 inches in distance
int oneFoot=(.955*fullRotation); //oneFoot = 12 inches or 343.95
int oneInch=(oneFoot/12);  //moves one inch
int Spin=(oneInch*19.73)+40; //180 degree spin +40 for calibration
int halfSpin=(Spin/2);  //90 degree spin
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void StarWars()
{
	playTone(695, 14);
	playTone(695, 14);
	playTone(695, 14);
	playTone(929, 83);
	playTone(1401, 83);
	playTone(1251, 14);
	playTone(1188, 14);
	playTone(1054, 14);
	playTone(1841, 83);
	playTone(1401, 41);
	playTone(1251, 14);
	playTone(1188, 14);
	playTone(1054, 14);
	playTone(1841, 83);
	playTone(1401, 41);
	playTone(1251, 14);
	playTone(1188, 14);
	playTone(1251, 14);
	playTone(1054, 55);
	wait1Msec(280);
	playTone(695, 14);
	playTone(695, 14);
	playTone(695, 14);
	playTone(929, 83);
	playTone(1401, 83);
	playTone(1251, 14);
	playTone(1188, 14);
	playTone(1054, 14);
	playTone(1841, 83);
	playTone(1401, 41);
	playTone(1251, 14);
	playTone(1188, 14);
	playTone(1054, 14);
	playTone(1841, 83);
	playTone(1401, 41);
	playTone(1251, 14);
	playTone(1188, 14);
	playTone(1251, 14);
	playTone(1054, 55);
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void BeethovenFifth()
{
	//  Piano Player II
	//    rest);
	wait10Msec(75);
	playTone(784,15);	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(622,38);	wait10Msec(38);
	//    rest);
	wait10Msec(38);
	playTone(698,15);	wait10Msec(19);
	playTone(698,15);	wait10Msec(19);
	playTone(698,15);	wait10Msec(19);
	playTone(587,38);	wait10Msec(38);
	//    rest);
	wait10Msec(75);
	playTone(784,15);	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(622,15);	wait10Msec(19);
	playTone(831,15);	wait10Msec(19);
	playTone(831,15);	wait10Msec(19);
	playTone(831,15);	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(1244,15);	wait10Msec(19);
	playTone(1244,15);	wait10Msec(19);
	playTone(1244,15);	wait10Msec(19);
	playTone(1047,38);	wait10Msec(38);
	//    rest);
	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(587,15);	wait10Msec(19);
	playTone(831,15);	wait10Msec(19);
	playTone(831,15);	wait10Msec(19);
	playTone(831,15);	wait10Msec(19);
	playTone(784,15);	wait10Msec(19);
	playTone(1397,15);	wait10Msec(19);
	playTone(1397,15);	wait10Msec(19);
	playTone(1397,15);	wait10Msec(19);
	playTone(1175,38);	wait10Msec(38);
	//    rest);
	wait10Msec(19);
	playTone(1568,15);	wait10Msec(19);
	playTone(1568,15);	wait10Msec(19);
	playTone(1397,15);	wait10Msec(19);
	playTone(1244,19);	wait10Msec(19);
	//    rest);
	wait10Msec(19);
	playTone(1175,15);	wait10Msec(19);
	playTone(1568,15);	wait10Msec(19);
	playTone(1568,15);	wait10Msec(19);
	playTone(1397,15);	wait10Msec(19);
	playTone(1244,19);	wait10Msec(19);
	//    rest);
	wait10Msec(19);
	playTone(1175,15);	wait10Msec(19);
	playTone(1568,15);	wait10Msec(19);
	playTone(1568,15);	wait10Msec(19);
	playTone(1397,15);	wait10Msec(19);
	playTone(1244,19);	wait10Msec(19);
	//    rest);
	wait10Msec(38);
	playTone(1047,19);	wait10Msec(19);
	//    rest);
	wait10Msec(38);
	playTone(784,38);	wait10Msec(38);
	return;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void HallOfMountainKing()
{
	wait10Msec(8);  // Rest
	playTone(220,12);  wait10Msec(15);
	playTone(247,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(294,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(330,24);  wait10Msec(30);
	playTone(311,12);  wait10Msec(15);
	playTone(247,12);  wait10Msec(15);
	playTone(311,24);  wait10Msec(30);
	playTone(294,12);  wait10Msec(15);
	playTone(233,12);  wait10Msec(15);
	playTone(294,24);  wait10Msec(30);
	playTone(220,12);  wait10Msec(15);
	playTone(247,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(294,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(392,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(392,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	playTone(220,12);  wait10Msec(15);
	playTone(247,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(294,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(330,24);  wait10Msec(30);
	playTone(311,12);  wait10Msec(15);
	playTone(247,12);  wait10Msec(15);
	playTone(311,24);  wait10Msec(30);
	playTone(294,12);  wait10Msec(15);
	playTone(233,12);  wait10Msec(15);
	playTone(294,24);  wait10Msec(30);
	playTone(220,12);  wait10Msec(15);
	playTone(247,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(294,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(392,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(262,12);  wait10Msec(15);
	playTone(330,12);  wait10Msec(15);
	playTone(392,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	playTone(330,12);  wait10Msec(15);
	playTone(370,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(494,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(494,24);  wait10Msec(30);
	playTone(523,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(523,24);  wait10Msec(30);
	playTone(494,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(494,24);  wait10Msec(30);
	playTone(330,12);  wait10Msec(15);
	playTone(370,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(494,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(494,24);  wait10Msec(30);
	playTone(523,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(523,24);  wait10Msec(30);
	playTone(494,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	playTone(330,12);  wait10Msec(15);
	playTone(370,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(494,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(494,24);  wait10Msec(30);
	playTone(523,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(523,24);  wait10Msec(30);
	playTone(494,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(494,24);  wait10Msec(30);
	playTone(330,12);  wait10Msec(15);
	playTone(370,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(494,12);  wait10Msec(15);
	playTone(415,12);  wait10Msec(15);
	playTone(494,24);  wait10Msec(30);
	playTone(523,12);  wait10Msec(15);
	playTone(440,12);  wait10Msec(15);
	playTone(523,24);  wait10Msec(30);
	playTone(494,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	wait10Msec(8);  // Rest
	playTone(440,8);  wait10Msec(15);
	playTone(494,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(587,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(659,24);  wait10Msec(30);
	playTone(622,8);  wait10Msec(15);
	playTone(494,8);  wait10Msec(15);
	playTone(622,24);  wait10Msec(30);
	playTone(587,8);  wait10Msec(15);
	playTone(466,8);  wait10Msec(15);
	playTone(587,24);  wait10Msec(30);
	playTone(440,8);  wait10Msec(15);
	playTone(494,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(587,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(880,8);  wait10Msec(15);
	playTone(784,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(784,48);  wait10Msec(60);
	wait10Msec(8);  // Rest
	playTone(440,8);  wait10Msec(15);
	playTone(494,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(587,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(659,24);  wait10Msec(30);
	playTone(622,8);  wait10Msec(15);
	playTone(494,8);  wait10Msec(15);
	playTone(622,24);  wait10Msec(30);
	playTone(587,8);  wait10Msec(15);
	playTone(466,8);  wait10Msec(15);
	playTone(587,24);  wait10Msec(30);
	playTone(440,8);  wait10Msec(15);
	playTone(494,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(587,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(523,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(880,8);  wait10Msec(15);
	playTone(831,8);  wait10Msec(15);
	playTone(659,8);  wait10Msec(15);
	playTone(831,8);  wait10Msec(15);
	playTone(988,8);  wait10Msec(15);
	playTone(880,48); wait10Msec(60);
	return;
}
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
void FrereJacque()
{
	playTone(523,40);	wait10Msec(50);
	playTone(587,40);	wait10Msec(50);
	playTone(659,40);	wait10Msec(50);
	playTone(523,40);	wait10Msec(50);
	playTone(523,40);	wait10Msec(50);
	playTone(587,40);	wait10Msec(50);
	playTone(659,40);	wait10Msec(50);
	playTone(523,40);	wait10Msec(50);
	playTone(659,40);	wait10Msec(50);
	playTone(698,40);	wait10Msec(50);
	playTone(784,80);	wait10Msec(90);
	playTone(659,40);	wait10Msec(50);
	playTone(698,40);	wait10Msec(50);
	playTone(784,80);	wait10Msec(90);
	playTone(784,20);	wait10Msec(30);
	playTone(880,20);	wait10Msec(30);
	playTone(784,20);	wait10Msec(30);
	playTone(698,20);	wait10Msec(30);
	playTone(659,40);	wait10Msec(50);
	playTone(523,40);	wait10Msec(50);
	playTone(784,20);	wait10Msec(30);
	playTone(880,20);	wait10Msec(30);
	playTone(784,20);	wait10Msec(30);
	playTone(698,20);	wait10Msec(30);
	playTone(659,40);	wait10Msec(50);
	playTone(523,40);	wait10Msec(50);
	playTone(523,40);	wait10Msec(50);
	playTone(392,40);	wait10Msec(50);
	playTone(523,80);	wait10Msec(90);
	playTone(523,40);	wait10Msec(50);
	playTone(392,40);	wait10Msec(50);
	playTone(523,80);	wait10Msec(90);
	return;
}

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~//
//task main()
//{
//	SensorValue[rencoder]=0; //Reset Right encoder
//	SensorValue[lencoder]=0; //Reset Left encoder
//	while(true)
//	{

////HallOfMountainKing()
////wait10Msec(0);
////		FrereJacque();
////		wait10Msec(50);
////		StarWars();
////		wait10Msec(100);
////		BeethovenFifth();
////		wait10Msec(50);
////		motor[left]=vexRT[Ch3];
////		motor[right]=vexRT[Ch2];
////		motor[arm]=vexRT[Ch4];
////		motor[claw]=vexRT[Ch1];
////		//			motor[arm]=vexRT[Ch];
////		//motor[arm]=-vexRT[Ch];
////		//	motor[claw]=vexRT[Btn];
////		//	motor[claw]=-vexRT[Btn];

//	}

//}
