#pragma config(Sensor, dgtl1,  enc,            sensorQuadEncoder)
#pragma config(Motor,  port1,           Angle,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "anglePID.c"
task main()
{
	SensorValue[enc] = 0;
	wait1Msec(1000);
	startTask(anglePIDControl);
//pidRunning = 1;
//while(1)
	//motor[port1] = 127;

}
